api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "promo-price-transform"
type = "function"
uid = "e9ae82e8-8ed7-1ac2-4cf1-f01e88ba9c5a1d62604e"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
