api_version = "2026-04"

[[extensions]]
name = "orderfix"
handle = "orderfix"
type = "ui_extension"
uid = "74847f36-4079-4ce7-cd03-9117922abb4b9830a893"

[[extensions.targeting]]
module = "./src/ThankYou.jsx"
target = "purchase.thank-you.block.render"

[[extensions.targeting]]
module = "./src/OrderStatus.jsx"
target = "customer-account.order-status.block.render"

[extensions.capabilities]
api_access = true
network_access = true